title: Fractal Hardware | Design, Engineering, Prototyping
company: Fractal, LLC
phone: 615.930.1206
address: 'Upper Hill Suite 7 | 2100 Dunn Avenue Nashville, TN, 37211'
email: team@fractalhardware.com
description: "Fractal uses mechanical, electrical, and industrial design to prototype and engineer manufactured products for the internet of things, medical devices, and more"
url: http://fractalhardware.com
analytics: UA-81873109-1
type: image/png
logo: /assets/brand/fractal-logo.svg
logo-square: /assets/brand/Fractal-Square-Color.png
logo-banner: /assets/brand/Fractal-Banner-Color.png

# Build settings
markdown: kramdown
permalink: /posts/:title/
plugins:
  - font-awesome-sass
  - uglifier
  - sass
  - jemoji
  - jekyll-sitemap
  - jekyll-assets

collections:
  public:
    output: true
    permalink: /

assets:
  compress:
    css: true
    js: true
  autowrite: true
  assets:
    - "*.png"
    - "*.svg"
    - "*.jpg"
  sources:
    - _assets/css
    - _assets/img
    - _assets/js
