title: Fractal Hardware
email: team@fractalhardware.com
description: > # this means to ignore newlines until "baseurl:"
  Fractal Hardware Design
url: "http://fractalhardware.com" # the base hostname & protocol for your site
analytics: UA-81873109-1

# Build settings
markdown: kramdown
permalink: /posts/:title/
gems:
  - jemoji
  - jekyll-sitemap
