title: Fractal Hardware
company: Fractal, LLC
address: 533 Church St. Suite 133 Nashville, TN 37219
email: team@fractalhardware.com
description: Fractal Hardwarean is an elite and nimble hardware design team
url: "http://fractalhardware.com"
analytics: UA-81873109-1

# Build settings
markdown: kramdown
permalink: /posts/:title/
gems:
  - jemoji
  - jekyll-sitemap
