title: Fractal Hardware
company: Fractal, LLC
phone: 615.930.1206
address: 533 Church St. Suite 133 Nashville, TN 37219
email: team@fractalhardware.com
description: "hardware design: concept to manufacture"
url: "http://fractalhardware.com"
analytics: UA-81873109-1

# Build settings
markdown: kramdown
permalink: /posts/:title/
gems:
  - jemoji
  - jekyll-sitemap
