title: Fractal Hardware
company: Fractal, LLC
phone: 615.930.1206
address: '41 Peabody Street #121 Nashville, TN 37210'
email: team@fractalhardware.com
description: "Fractal uses mechanical, electrical, and industrial design to prototype and develop products for mass production. We are as crazy about great client experiences as we are about designing disruptive products"
url: "http://fractalhardware.com"
analytics: UA-81873109-1

# Build settings
markdown: kramdown
permalink: /posts/:title/
gems:
  - jemoji
  - jekyll-sitemap
